on:
  push:
    branches: main
  workflow_dispatch:

name: Render Report

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0' # The R version to download (if necessary) and use.
 
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
            packages:
               any::knitr
               any::rmarkdown
               any::jsonlite
               any::dplyr
               any::ggplot2
               any::readr
               any::lubridate
               any::forcats

      - name: Render document
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          path: mn_covid_report.qmd

    - name: Setup git config
        run: |
# setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit
        run: |
          # Stage the file, commit and push
          git add mn_covid_report.html
          git commit -m "Updated report"
          git push origin master
          
# - name: Upload rendered document
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: rendered_doc
      #     path: mn_covid_report.html